name: 'my first container action'
description: 'Cloud Chase Container Actions'
author: 'Cloud Chase'
inputs:
  myInput:
    description: 'greeting to use'
    required: true
    default: 'Awesome Guru'
outputs:
  myOutput:
    description: 'total memory'
runs:
  using: 'docker'
  image: 'Dockerfile'
